credentials:
  usernames:
    abc:
      email: jsmith@gmail.com
      name: aaa
      password: abc # To be replaced with hashed password
    admin:
      email: rbriggs@gmail.com
      name: user
      password: 123 # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com